import { CONFIG } from './config'

export const DEFS = [
"s/he moves abruptly to different location, position, etc.",
"s/he is stern, severe, strict",
"she goes into heat",
"tent caterpillar, army worm",
"s/he is the same in amount or number as previously",
"look at h/! look at them!",
"eastern skunk cabbage",
"extending or moving behind or in back of; extending or moving out of view or out of sight",
"s/he is brunette, has dark hair",
"fishing tackle",
"I wish that ..., I hope that ...",
"fisherman",
"s/he gets up",
"detouring around, bypassing;  around in a circle; encircling, orbiting",
"bee",
"s/he atones, is contrite, becomes humble",
"s/he sells, buys",
"s/he buys or sells",
"as if",
"s/he is back from having cooked",
"s/he is back from digging",
"s/he is back from having played game; s/he is back from having run for office , is back from having competed",
"again in the future;  good-bye, farewell",
"s/he, it keeps going, is still going",
"s/he pays",
"s/he has come back having gained weight",
"officer",
"s/he has small face",
"s/he is back from having checked traps",
"it is turned inside-out, is folded back",
"there is more of h/",
"more, more so",
"there is mild weather in winter, a thaw, causing fallen snow to become moist",
"angel, cherub",
"s/he sees what will happen to self in future, s/he has premonition;",
"in the distant past, way back then",
"at an angle, diagonally, obliquely, crooked",
"it is tattooed",
"s/he has wrinkles or crow's feet on face",
"the level of the tide changes",
"s/he changes seat, moves to another seat; s/he changes position in seat",
"s/he changes clothes",
"seldom, rarely",
"s/he seldom dances",
"it would have to ...",
"tree-stump; butt end of log",
"porpoise tail fin or dorsal fin",
"juggler",
"charm basket",
"rust",
"chowder",
"vein",
"jacket",
"day breaks, dawn comes",
"it is daybreak, is dawn",
"s/he hemorrhages through nose and mouth",
"jackpot",
"s/he is helpless",
"s/he is in out-of-the-way place, is inaccessible",
"s/he, it comes from there",
"s/he quiets down",
"s/he is silent, sits silently",
"s/he, it is bruised",
"s/he leaves mark by sitting",
"chimney, smokestack",
"s/he, it is low",
"it is low, goes along at low altitude",
"s/he has nightmare",
"h/ hair looks messy",
"toward here; recently",
"s/he, it comes toward here",
"soul, spirit",
"yikes!, whoops!, ugh!, yuck!, etc.",
"insect, bug",
"Atlantic harbor porpoise",
"s/he hedges bets;  s/he antes up",
"s/he hesitates out of shyness",
"s/he stops fishing",
"s/he, it stops moving through the air",
"s/he, it stops going there",
"it hangs, hangs down, dangles",
"event, occurrence, happening; truth, the way it is",
"the way s/he looks; s/he is ugly",
"it is below, it is at the bottom, it is downstairs",
"umpire",
"s/he races",
"s/he, it is half full of liquid",
"s/he stops shooting",
"s/he stops being afraid",
"s/he stops barking",
"water or dampness comes through h/, it",
"it is chilled all the way through;  cold comes through it",
"it leaks through with the liquid accumulating",
"raccoon",
"s/he is last one left, is left over",
"s/he walks through",
"back and forth",
"up, upward, up above",
"s/he sits upright, sits up above",
"it is up",
"sturdy grass used for basket handles, in craftwork, etc.",
"one to each",
"s/he stays right there, stays the hell there",
"there is praying or prayer service, there is mass, there is church service",
"hey!, listen!, look!",
"because; because of course",
"what is said; expression, saying",
"s/he, it moves out of sight",
"many times, several times;  many, several",
"s/he hides h/",
"something old, antique, antiquated, archaic, etc.",
"cup",
"railroad",
"corset",
"better not; don't!",
"would not",
"not, not at all",
"it is hidden or concealed; it is clandestine",
"s/he hides it, conceals it",
"s/he, it is rough to the touch, is rough in texture",
"street corner",
"ketchup",
"it is so much, there is so much of it;  they are so many, there are so many of them",
"of course, sure enough",
"a little, a little bit; slightly",
"all day",
"can",
"captain; tribal council-member, official equivalent to kinap",
"unintentionally;  accidentally",
"door",
"garden",
"s/he looks intently, glares",
"s/he, it is sharp",
"s/he is big, bulky",
"s/he falls over",
"orphan",
"s/he is ready",
"s/he fell down, fell on the ground or floor",
"s/he is ready",
"s/he is full-grown, grown up, adult",
"it is low tide;  it is a day, the day is ..., the weather is ...",
"s/he sat down, can sit down;  s/he sat up, can sit up;  s/he is done cooking, is ready to eat",
"sun, moon; month",
"ice giant",
"muskrat",
"clock, timepiece",
"s/he hogs food, money, supplies, etc.",
"s/he freezes, is frozen",
"s/he, it sticks, is stuck, is caught;  s/he alights and holds on",
"s/he is on, stuck on; s/he is in hock, still in hock",
"s/he speaks",
"s/he dives",
"handkerchief",
"it is frozen shut, is frozen over; the entrance to it is frozen shut",
"s/he stays longer because of the cold",
"it is steep hill",
"it has strong scent or odor",
"s/he likes the place so much that s/he stays longer",
"s/he sings as s/he enters",
"it hurts",
"s/he walks in;  s/he rises farther to the north each day",
"it is badly scratched",
"s/he is wide, is broad",
"s/he, it is wide, is broad",
"it is dark in color",
"s/he goes about openly",
"s/he is helpless, is in hopeless or dangerous situation; s/he is held accountable or responsible, is blamed",
"there is sand or gravel on or mixed in the snow; there are gravelly patches showing through the snow",
"there is big dance",
"spring; cold water",
"big log for fire",
"s/he feels cold",
"lake",
"hawk",
"s/he feels cold",
"cellar, basement",
"s/he, it is bent thus, curves thus",
"attic; closet",
"s/he makes that much money; h/ wage or salary is so much",
"s/he sees something; s/he pictures something in mind",
"bandanna, kerchief, headband",
"s/he climbs, clambers",
"s/he, it costs that much, is worth so much",
"rail",
"s/he smiles or laughs thus",
"lemon",
"it happens; something happens to it",
"it looks thus, it is such and such a kind",
"s/he, it rolls thus, there",
"s/he makes such a facial expression",
"it happens thus",
"s/he is named ..., is called ...; h/ name is ...",
"fresh water, lake water; body of fresh water",
"s/he lies down; s/he is lying down;  she is confined",
"it is a work week ; it is a weekday",
"s/he leaves, departs; s/he goes home",
"s/he grows up;  s/he starts to grow",
"s/he extends from there, exists from there onward, is in place beginning then",
"dress",
"sap of sugar maple; maple syrup or sugar; anything sweet",
"fiddlehead",
"s/he is lazy",
"the tide is not particularly high or low",
"shopkeeper",
"wolf; name of Koluskap's twin brother",
"baseboard, mopboard",
"s/he, it comes together",
"mustard",
"it comes together",
"s/he calls them together, s/he convokes them",
"s/he, it comes together, gathers, collects;  s/he takes part in gathering;  they come together, they go as group",
"s/he takes part in meeting or gathering;  they sit together, they are positioned together; they meet , they collect , they are a group or coalition",
"approximately, about",
"match, lighter",
"ending, terminating, concluding, finishing; having ended, terminated, concluded, finished",
"s/he fits through",
"s/he fits in place, there is room for h/; s/he has had enough of sitting",
"why not",
"s/he has run out",
"it is late",
"it is eaten, is edible",
"s/he gets in the way of something or someone",
"Mi'kmaq",
"s/he looks all around",
"s/he goes to many different places",
"s/he sits in different positions, shifts from one position to another",
"s/he gives, donates",
"h/ clothing is covered with grease;  s/he is greasy",
"s/he oils or greases h/ using brush, paper, etc.",
"h/ face is shiny",
"minute",
"s/he catches cold again",
"often, sometimes",
"it is plentiful, there is enough of it to go around",
"wadding",
"s/he is in the way, obstructs, sits in the way",
"it goes off course;  s/he is a ball",
"article of clothing, garment",
"s/he is clumsy",
"s/he holds bad hand",
"s/he has messy or disheveled hair",
"striped bass, sea bass, black bass",
"milk",
"s/he, it falls off, flies off",
"s/he, it has become detached, is not attached",
"island",
"s/he is crowded out;  they grow in scattered clumps",
"s/he swells; s/he is swollen",
"h/ heart",
"h/ chest",
"woman friend of a woman; lady, my dear",
"s/he is heard going",
"s/he is heard dancing",
"deep, in bottom of hole",
"s/he cuts hair; s/he barbers",
"clear sky, blue sky",
"it clears",
"s/he cuts own hair",
"s/he picks or gathers berries",
"down, downward; down to lower position",
"s/he grows slowly",
"s/he is slow",
"s/he goes slowly",
"number, numeral; telephone number",
"five-hundred",
"rooster",
"s/he strings h/",
"s/he sleeps in someone else's house so that person won't be alone",
"s/he goes to fish",
"s/he goes to swim",
"if; in case",
"to or at a destination or starting-point;  at, in, to my house",
"somehow; in some unknown way; just by chance",
"s/he coughs",
"s/he goes under",
"four-hundred",
"there are four of them, they are group of four",
"it heals",
"s/he growls",
"s/he goes out at night, travels at night; s/he stays out late at night",
"s/he is married",
"two-hundred",
"that, that one",
"it is arid, is dry",
"s/he is afraid",
"s/he has a set way of life; h/ ways are set",
"fish",
"she nurses or breast-feeds baby; she is wet-nurse",
"s/he looks around to see what's going on, noses around, observes, browses, wanders around looking",
"she-bear",
"on top of;  on top of that, what's more",
"s/he sits at low level, has low position",
"s/he hears self",
"s/he goes out, comes out",
"dancer",
"s/he hears",
"across, on the other side",
"across, on the other side",
"s/he is deaf",
"s/he gathers driftwood",
"it is that soiled, is that dirty",
"s/he behaves thus",
"it runs thus, its course is ...",
"s/he weighs so much",
"s/he is right there, stays right there",
"s/he increases in quantity;  they increase in number",
"away",
"in that direction, toward; in that way",
"s/he sits thus",
"s/he cuts thus",
"s/he dresses thus",
"h/ foot is like that; h/ feet are like that",
"only",
"s/he mixes bread dough",
"s/he sits down quickly",
"s/he lands, arrives by boat ashore where water is shallow , s/he runs canoe ashore",
"lagoon, bay; sheltered harbor, port",
"canoe",
"it recoils, has a kick to it",
"s/he steadies or braces for accurate aim",
"lamb",
"it is in there;  it is loaded",
"s/he hunts deer",
"in back yard, out back; behind",
"box",
"h/ face is uncovered or exposed",
"s/he, it comes to open place",
"popcorn",
"downriver, downstream; downhill",
"s/he is frozen in thick layer",
"s/he chokes, gets dizzy and sick from inhaling smoke",
"especially",
"s/he, it arrives, reaches there",
"bat",
"fresh food obtained when in season",
"banjo",
"one",
"s/he, it falls or flies to there",
"s/he approaches or arrives swimming, swims here",
"s/he reaches a size",
"s/he extends to there",
"quilt, blanket",
"it builds up, picks up; wind comes up",
"s/he moves to here, into here",
"peach",
"pitcher, jug",
"Pequot",
"lion",
"pickax",
"vest",
"pork soup, pork broth",
"pork",
"s/he has thick coat of fur",
"paper",
"s/he, it is new",
"lead",
"pin",
"s/he plays wind instrument",
"s/he, it is hollow",
"pith",
"s/he, it falls in",
"s/he looks inside, peers into",
"s/he, it goes in or comes in",
"s/he moves in",
"piece of firewood; piece of wood",
"hair",
"s/he is burned, scorched",
"it is burned, scorched",
"s/he selects, chooses, picks",
"shoe",
"splat!",
"plum",
"prune",
"s/he goes on falling; s/he, it continues on original course",
"s/he is growing, keeps growing",
"s/he goes along",
"s/he is moving belongings or household",
"it holds so much",
"drop of water, raindrop",
"ice floe, reef of ice",
"s/he shines red",
"s/he earns",
"s/he has red hair, is redhead",
"h/ skin is red",
"hailstone, icicle",
"it is continuous sheet, is seamless",
"springtail, snow flea; fruit fly",
"s/he has contagious disease",
"splitting",
"s/he tells on self, confesses",
"it is found",
"s/he turns to one side while moving along, turns off onto side road, changes direction in which s/he is going",
"root of white or yellow water lily",
"blade of grass, strand of hay, straw",
"s/he escapes, breaks loose",
"s/he, it is full of liquid",
"it is full",
"s/he, it is intact, is whole, is not smashed;  s/he is healthy",
"heart",
"cat",
"s/he hooks fish",
"s/he turns to side while dancing",
"bag",
"maggot",
"bow",
"bottle",
"bubble",
"small bowl",
"s/he puts h/, places h/",
"it is put there, is installed; it is donated",
"s/he sets traps",
"of winter",
"in the north",
"boarder, tourist",
"little boat",
"s/he blows; s/he spouts",
"quahog",
"quarter-hour; quarter",
"bead",
"h/ clothing is dirty or soiled; s/he is dirty, is soiled",
"s/he, it is dirty",
"s/, it falls away",
"h/ shin guard",
"quart bottle",
"s/he avoids eye-contact, averts gaze",
"s/he sees that far",
"s/he, it is so long",
"s/he goes so far; s/he goes for so long a time, is gone for so long a time",
"h/ pace is so long",
"s/he takes so long to return",
"lake",
"pool, pond, lagoon",
"s/he is respectful",
"needle, syringe",
"jellyfish",
"fast, quickly, rapidly, swiftly",
"there is too much of h/, there is excess of h/;  there are too many of them",
"s/he abuts or touches",
"halibut",
"thirteen",
"s/he is extremely sensitive to touch; s/he is sore, tender",
"s/he is hypersensitive to pain; s/he reacts to any touch as if it were painful",
"s/he, it passes through, goes or comes through;  it turns out or happens",
"little shop, convenience store",
"sausage",
"sardine",
"s/he is so cold that s/he cries",
"s/he, it goes up to something",
"pail, bucket",
"it is hard to do, is difficult",
"s/he is stubborn, is fierce, is tough on others",
"s/he is hard to get at",
"widow; beetle; pear",
"s/he paddles alone",
"sinker",
"thirty",
"s/he dies hard",
"for a long time",
"bird",
"s/he, it is emptying, is empty",
"s/he is empty",
"s/he, it is empty",
"h/ eye; h/ face",
"eyeglasses;  monocle, catcher's or goalie's mask",
"s/he sits close",
"s/he gets mad easily, has quick temper",
"it fits snugly",
"green leaf",
"man",
"it is on top, it is on surface",
"female fish",
"bone",
"pumpkin",
"on or along St. Croix River ; at, to Schoodic Point, Gouldsboro, Maine",
"sloop, shallop; sailing ship, sailboat",
"smock",
"s/he feeds h/",
"cement",
"h/ daughter-in-law, h/ grandson's wife",
"upstairs",
"s/he blows nose",
"s/he is tight",
"s/he freezes along edge;  water freezes along h/ edge",
"weasel, ermine",
"h/ tail",
"saliva, spittle",
"it is tall; it is in high place",
"high in sky, in outer space, up as high as one can see",
"s/he is unintentionally involved in incident with others",
"s/he eats expensive food",
"upward",
"in the daytime, during the day",
"s/he rises high",
"it is left over, it is available for future or emergency use",
"small squash",
"s/he survives",
"along the edge",
"spark; ember, glowing coal, live coal",
"pint; pint jar or bottle; large ladle",
"s/he gets or has three points;  they are three in a boat, they travel three in a boat",
"s/he spits",
"it is smooth",
"like, as",
"doctor, physician",
"dulse",
"here and there;  thereabouts",
"at the garbage dump",
"somehow, somewhere; in a manner or place unknown",
"would somehow;  how would ...?",
"s/he leaves tracks from there, leaves tracks behind",
"it sticks out from there",
"s/he survives, lives through; s/he comes out alive",
"when",
"there is enough of h/, it; there is sufficient or adequate supply of h/, it",
"s/he is big enough",
"s/he loads items into boat or vehicle",
"deacon",
"it is cold to the touch",
"it is cold;  it is cool, it is suitable to wear in hot weather",
"s/he is heavy",
"it is heavy; it is a grave or serious matter",
"cold spring; cold water",
"s/he swims from there",
"s/he hits with it",
"playing card",
"s/he is growing",
"s/he is moving",
"s/he, it is broken",
"s/he, it breaks in two, breaks apart, breaks off",
"s/he dodges, gets out of the way, ducks",
"h/ spot; h/ bed",
"twin",
"marker, playing piece; checker; pawn",
"s/he watches attentively, stands guard",
"s/he is of certain age, s/he is so old",
"s/he, it goes by; s/he, it goes so fast",
"mouse",
"shed",
"s/he wakes up cold",
"s/he has boat or canoe",
"h/ boat",
"earth, ground, soil, dirt",
"s/he operates on h/",
"s/he has daughter; s/he is parent of daughter",
"h/ daughter",
"s/he swims by, swims past",
"s/he is so big",
"s/he is so far along; s/he is sitting at certain distance, is at certain location",
"s/he looks in or out",
"s/he is in there",
"s/he makes up with h/, makes amends to h/, apologizes to h/; talks to h/ pleasantly, pleads with h/",
"s/he cleans h/ when harvesting h/",
"old man; her husband, her old man",
"moss; old man's beard",
"oatmeal",
"s/he obtains h/, gets h/; s/he takes some of h/",
"swamp, bog, wetland",
"s/he, it is indented, is dented",
"s/he, it is hollow, is concave",
"whitecap",
"s/he, it is white",
"ash wood with whitish color",
"h/ face is white or pale",
"snowflake",
"in direction from which wind is blowing, to windward",
"s/he has regular ways, regular habits; h/ behavior is correct or proper",
"s/he finds out, investigates",
"s/he is found out; s/he knows where s/he is going",
"s/he lives in same building with other; s/he is roommate or housemate",
"s/he goes along, participates, attends;  s/he receives communion",
"h/ nose; h/ bill, h/ beak",
"s/he falls often",
"s/he goes frequently; s/he likes to go places",
"pith or center of stem",
"feather",
"s/he pulls, pulls away; s/he pulls away from previous position",
"the tide goes out; it is ebb tide",
"s/he hurries, goes hurriedly",
"s/he is in a hurry, in a rush",
"h/ wrist",
"medal",
"h/ eyebrow",
"meat",
"h/ scalp",
"s/he is gearing up, is getting ready, is preparing",
"fish scale",
"yesterday",
"s/he is right or correct",
"s/he, it goes straight; s/he is strike",
"s/he sees well, has good eyesight; s/he has unobstructed view",
"s/he is well off, affluent; s/he lives well, lives in comfort, is easy-going; s/he is in good shape, is in good situation",
"s/he is good; s/he is beautiful",
"s/he, it functions well; it shoots accurately;  s/he leads a good life;  very well, it's all right",
"s/he is nice and big",
"s/he dances well",
"s/he holds good hand",
"s/he is sitting nicely, comfortably; s/he is well off",
"s/he has gone to bed",
"s/he has nice hair;  s/he has nice fur",
"s/he gets up",
"nest",
"h/ knee",
"unless",
"each and every one individually",
"each one individually",
"this, this one",
]

if (CONFIG.normalization) {
  DEFS.forEach((val, i) => (DEFS[i] = val.normalize(CONFIG.normalization)))
}


